config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get "welcome/index"
    get "search", to: "search#questions"
    post "answer", to: "answer#question"
  end
  namespace :users_backoffice do
    get "welcome/index"
  end
  namespace :admins_backoffice do
    get "welcome/index"
    resources :admins
    resources :subjects
    resources :questions
  end
  
  devise_for :admins
  devise_for :users

  get "welcome", to: "site/welcome#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"

  root to: 'site/welcome#index'
  
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions
    
    # Kaminari
    paginates_per 10
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  before_action :verify_password, only: [:update]

  def index
    @admins = Admin.all.page(params[:page])
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice:"Administrator sucessfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice:"Administrator sucessfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end     
  end

  def destroy
    if @admin.destroy
      redirect_to admins_backoffice_admins_path, notice:"Administrator sucessfully deleted!"
    else
      render :index, status: :unprocessable_entity
    end   
  end

  private

  def set_admin
    @admin = Admin.find(params[:id])
  end

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def verify_password
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end

end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_subjects, only:[:edit, :new]


  def index
    @questions = Question.includes(:subject)
                         .order(:description)
                         .page(params[:page])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(params_question)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice:"Question sucessfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice:"Question sucessfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end     
  end

  def destroy
    if @question.destroy
      redirect_to admins_backoffice_questions_path, notice:"Question sucessfully deleted!"
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def set_question
    @question = Question.find(params[:id])
  end

  def params_question
    params.require(:question).permit(:description, :subject_id ,
      answers_attributes: [:id, :description, :correct, :_destroy])   
  end

  def get_subjects
    @subjects = Subject.all
  end

end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
  before_action :set_subject, only: [:edit, :update, :destroy]

  def index
    @subjects = Subject.all.order(:description).page(params[:page])
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(params_subject)
    if @subject.save
      redirect_to admins_backoffice_subjects_path, notice:"Subject sucessfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @subject.update(params_subject)
      redirect_to admins_backoffice_subjects_path, notice:"Subject sucessfully updated!"
    else
      render :edit, status: :unprocessable_entity
    end     
  end

  def destroy
    if @subject.destroy
      redirect_to admins_backoffice_subjects_path, notice:"Subject sucessfully deleted!"
    else
      render :index, status: :unprocessable_entity
    end
  end

  private

  def set_subject
    @subject = Subject.find(params[:id])
  end

  def params_subject
    params.require(:subject).permit(:description)
  end

end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper

  def translate_attribute(object = nil, method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      "Insert the correct params"
    end
  end

end

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: {action_message: 'Edit'}
 %>

app/views/admins_backoffice/subjects/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="my-4 border-bottom pb-2"><%= t('messages.listing', model: @subjects.model_name.human(count: @subjects.count)) %></h1>
  </div>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
        <th>#</th>
        <th><%= translate_attribute(@subjects, :description) %></th>
        <th>
          <div class="d-flex justify-content-center">
            <%= link_to new_admins_backoffice_subject_path, class: "btn btn-success btn-circle btn-sm" do %>
              <i class="fa fa-plus"></i>
            <% end %>
          </div>
        </th>
      </tr>
    </thead>
    <tbody>
      <% @subjects.each do |subject| %>
        <tr>
          <td class="id-column"><%= subject.id %></td>
          <td><%= subject.description %></td>
          <td class="text-center" style="width: 120px">
            <%= link_to edit_admins_backoffice_subject_path(subject), class:"btn btn-primary btn-circle btn-sm" do %>
              <i class="fa fa-edit"></i>
            <% end %>
            <%= link_to admins_backoffice_subject_path(subject), data: { turbo_method: :delete, turbo_confirm: t('messages.confirm_with', item: subject.description.truncate(60)) }, class: "btn btn-danger btn-circle btn-sm" do %>
              <i class="fa fa-minus"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="d-flex justify-content-center">
    <%= paginate @subjects %>
  </div>
</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
           locals: {action_message: 'New'}
 %>